import { InternalServerError, PropertyNotFoundException, RentalValidationException, UnauthorizedException, ValidationException } from "../models/models_0";
import { AssignPropertyManagerServerInput, AssignPropertyManagerServerOutput } from "../server/operations/AssignPropertyManager";
import { BecomeLandlordServerInput, BecomeLandlordServerOutput } from "../server/operations/BecomeLandlord";
import { CreatePropertyServerInput, CreatePropertyServerOutput } from "../server/operations/CreateProperty";
import { DeletePropertyServerInput, DeletePropertyServerOutput } from "../server/operations/DeleteProperty";
import { ForgotPasswordServerInput, ForgotPasswordServerOutput } from "../server/operations/ForgotPassword";
import { GetMediaUploadUrlServerInput, GetMediaUploadUrlServerOutput } from "../server/operations/GetMediaUploadUrl";
import { GetNearbyPropertiesServerInput, GetNearbyPropertiesServerOutput } from "../server/operations/GetNearbyProperties";
import { GetPropertiesByLocationServerInput, GetPropertiesByLocationServerOutput } from "../server/operations/GetPropertiesByLocation";
import { GetPropertyServerInput, GetPropertyServerOutput } from "../server/operations/GetProperty";
import { GetUserServerInput, GetUserServerOutput } from "../server/operations/GetUser";
import { ListLandlordPropertiesServerInput, ListLandlordPropertiesServerOutput } from "../server/operations/ListLandlordProperties";
import { ListManagedPropertiesServerInput, ListManagedPropertiesServerOutput } from "../server/operations/ListManagedProperties";
import { ListPropertiesServerInput, ListPropertiesServerOutput } from "../server/operations/ListProperties";
import { MarkPropertyAsAvailableServerInput, MarkPropertyAsAvailableServerOutput } from "../server/operations/MarkPropertyAsAvailable";
import { MarkPropertyAsRentedServerInput, MarkPropertyAsRentedServerOutput } from "../server/operations/MarkPropertyAsRented";
import { RemovePropertyManagerServerInput, RemovePropertyManagerServerOutput } from "../server/operations/RemovePropertyManager";
import { ResetPasswordServerInput, ResetPasswordServerOutput } from "../server/operations/ResetPassword";
import { ReviewLandlordApplicationServerInput, ReviewLandlordApplicationServerOutput } from "../server/operations/ReviewLandlordApplication";
import { SearchPropertiesServerInput, SearchPropertiesServerOutput } from "../server/operations/SearchProperties";
import { SignInServerInput, SignInServerOutput } from "../server/operations/SignIn";
import { SignUpServerInput, SignUpServerOutput } from "../server/operations/SignUp";
import { UpdatePropertyServerInput, UpdatePropertyServerOutput } from "../server/operations/UpdateProperty";
import { UpdatePropertyStatusServerInput, UpdatePropertyStatusServerOutput } from "../server/operations/UpdatePropertyStatus";
import { UpdateUserServerInput, UpdateUserServerOutput } from "../server/operations/UpdateUser";
import { VerifyEmailServerInput, VerifyEmailServerOutput } from "../server/operations/VerifyEmail";
import { ServerSerdeContext, SmithyFrameworkException as __SmithyFrameworkException } from "@aws-smithy/server-common";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@smithy/protocol-http";
import { SerdeContext as __SerdeContext } from "@smithy/types";
export declare const deserializeAssignPropertyManagerRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<AssignPropertyManagerServerInput>;
export declare const deserializeBecomeLandlordRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<BecomeLandlordServerInput>;
export declare const deserializeCreatePropertyRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<CreatePropertyServerInput>;
export declare const deserializeDeletePropertyRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<DeletePropertyServerInput>;
export declare const deserializeForgotPasswordRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<ForgotPasswordServerInput>;
export declare const deserializeGetMediaUploadUrlRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<GetMediaUploadUrlServerInput>;
export declare const deserializeGetNearbyPropertiesRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<GetNearbyPropertiesServerInput>;
export declare const deserializeGetPropertiesByLocationRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<GetPropertiesByLocationServerInput>;
export declare const deserializeGetPropertyRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<GetPropertyServerInput>;
export declare const deserializeGetUserRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<GetUserServerInput>;
export declare const deserializeListLandlordPropertiesRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<ListLandlordPropertiesServerInput>;
export declare const deserializeListManagedPropertiesRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<ListManagedPropertiesServerInput>;
export declare const deserializeListPropertiesRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<ListPropertiesServerInput>;
export declare const deserializeMarkPropertyAsAvailableRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<MarkPropertyAsAvailableServerInput>;
export declare const deserializeMarkPropertyAsRentedRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<MarkPropertyAsRentedServerInput>;
export declare const deserializeRemovePropertyManagerRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<RemovePropertyManagerServerInput>;
export declare const deserializeResetPasswordRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<ResetPasswordServerInput>;
export declare const deserializeReviewLandlordApplicationRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<ReviewLandlordApplicationServerInput>;
export declare const deserializeSearchPropertiesRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<SearchPropertiesServerInput>;
export declare const deserializeSignInRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<SignInServerInput>;
export declare const deserializeSignUpRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<SignUpServerInput>;
export declare const deserializeUpdatePropertyRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<UpdatePropertyServerInput>;
export declare const deserializeUpdatePropertyStatusRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<UpdatePropertyStatusServerInput>;
export declare const deserializeUpdateUserRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<UpdateUserServerInput>;
export declare const deserializeVerifyEmailRequest: (output: __HttpRequest, context: __SerdeContext) => Promise<VerifyEmailServerInput>;
export declare const serializeAssignPropertyManagerResponse: (input: AssignPropertyManagerServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeBecomeLandlordResponse: (input: BecomeLandlordServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeCreatePropertyResponse: (input: CreatePropertyServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeDeletePropertyResponse: (input: DeletePropertyServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeForgotPasswordResponse: (input: ForgotPasswordServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeGetMediaUploadUrlResponse: (input: GetMediaUploadUrlServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeGetNearbyPropertiesResponse: (input: GetNearbyPropertiesServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeGetPropertiesByLocationResponse: (input: GetPropertiesByLocationServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeGetPropertyResponse: (input: GetPropertyServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeGetUserResponse: (input: GetUserServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeListLandlordPropertiesResponse: (input: ListLandlordPropertiesServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeListManagedPropertiesResponse: (input: ListManagedPropertiesServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeListPropertiesResponse: (input: ListPropertiesServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeMarkPropertyAsAvailableResponse: (input: MarkPropertyAsAvailableServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeMarkPropertyAsRentedResponse: (input: MarkPropertyAsRentedServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeRemovePropertyManagerResponse: (input: RemovePropertyManagerServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeResetPasswordResponse: (input: ResetPasswordServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeReviewLandlordApplicationResponse: (input: ReviewLandlordApplicationServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeSearchPropertiesResponse: (input: SearchPropertiesServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeSignInResponse: (input: SignInServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeSignUpResponse: (input: SignUpServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeUpdatePropertyResponse: (input: UpdatePropertyServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeUpdatePropertyStatusResponse: (input: UpdatePropertyStatusServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeUpdateUserResponse: (input: UpdateUserServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeVerifyEmailResponse: (input: VerifyEmailServerOutput, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeFrameworkException: (input: __SmithyFrameworkException, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeInternalServerErrorError: (input: InternalServerError, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializePropertyNotFoundExceptionError: (input: PropertyNotFoundException, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeRentalValidationExceptionError: (input: RentalValidationException, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeUnauthorizedExceptionError: (input: UnauthorizedException, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
export declare const serializeValidationExceptionError: (input: ValidationException, ctx: ServerSerdeContext) => Promise<__HttpResponse>;
